#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
system_info:
  distro: ubuntu
  default_user:
    name: ubuntu
    shell: /bin/bash
network:
  version: 2
  renderer: NetworkManager
runcmd:
  - 'echo INSTALL SOLANA'
  - 'su ubuntu -c "curl -SfL https://release.solana.com/v1.10.25/install | sh -s"'
