#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
    # The following packages should be installed if you want to build yourself. that takes 45 min on a Ryzen 5 5600X at 4.2 GHz. do not recommend.
  - build-essential
  - gcc-multilib
  - libssl-dev
  - libudev-dev
  - pkg-config
  - zlib1g-dev
  - llvm
  - clang
  - cmake
  - make
  - libprotobuf-dev
  - protobuf-compiler
system_info:
  distro: ubuntu
  default_user:
    name: ubuntu
    shell: /bin/bash
runcmd:
    # Rust is only need if you want to build yourself.
  - 'echo INSTALL RUST'
  - 'su ubuntu -c "curl --tlsv1.2 https://sh.rustup.rs -Sf | sh -s -- -y"'
  - 'su ubuntu -c "echo source ~/.cargo/env >> ~/.profile"'
  - 'echo UPDATE RUST'
  - 'su ubuntu -c "source ~/.cargo/env && rustup update"'
  - 'su ubuntu -c "source ~/.cargo/env && rustup component add rustfmt"'
  - 'echo INSTALL SOLANA'
  - 'su ubuntu -c "cd ~ && git clone https://github.com/solana-labs/solana.git"'
  - 'su ubuntu -c "cd ~/solana && git checkout $(git describe --tags $(git rev-list --tags --max-count=1))"'
  - 'su ubuntu -c "source ~/.cargo/env && cd ~/solana && cargo build --release"'
  - 'su ubuntu -c "echo source ~/solana/target/release >> ~/.profile"'
